# Generated by Django 3.1.2 on 2021-01-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200, null=True)),
                ('content_date', models.DateTimeField(auto_now_add=True)),
                ('content_date_start', models.DateTimeField(blank=True, null=True)),
                ('content_date_end', models.DateTimeField(blank=True, null=True)),
                ('content_social_description', models.CharField(max_length=1000, null=True)),
                ('content_image', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('content_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.volunteer')),
                ('tags', models.ManyToManyField(to='events.Tag')),
            ],
        ),
    ]
