# Generated by Django 3.1.2 on 2021-01-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Story', 'Story')], max_length=200, null=True),
        ),
    ]
