# Generated by Django 3.1.2 on 2021-01-07 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_post_full_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attending',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
